# Generated by Django 5.2.7 on 2025-11-04 12:09

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', null=True, upload_to=usuarios.models.avatar_upload_path),
        ),
    ]
