# Generated by Django 5.2.5 on 2025-11-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_user.png', null=True, upload_to='avatars/'),
        ),
    ]
