# Generated by Django 5.2.7 on 2025-11-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('INGRESO', 'Ingreso'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('serie', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('ean_upc', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('uom_compra', models.CharField(choices=[('unidad', 'Unidad'), ('ml', 'ML'), ('litro', 'Litro'), ('kg', 'KG'), ('gramo', 'Gramo')], default='unidad', max_length=10)),
                ('uom_venta', models.CharField(choices=[('unidad', 'Unidad'), ('ml', 'ML'), ('litro', 'Litro'), ('kg', 'KG'), ('gramo', 'Gramo')], default='unidad', max_length=10)),
                ('factor_conversion', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('costo_estandar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('impuesto_iva', models.DecimalField(decimal_places=2, default=19.0, max_digits=5)),
                ('stock_actual', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('stock_maximo', models.IntegerField(blank=True, null=True)),
                ('punto_reorden', models.IntegerField(blank=True, null=True)),
                ('perishable', models.BooleanField(default=False)),
                ('control_por_lote', models.BooleanField(default=False)),
                ('control_por_serie', models.BooleanField(default=False)),
                ('imagen', models.ImageField(blank=True, default='default/default_product.png', null=True, upload_to='productos/')),
                ('ficha_tecnica', models.FileField(blank=True, null=True, upload_to='fichas/')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recepcion', models.CharField(max_length=50)),
                ('fecha_recepcion', models.DateTimeField()),
            ],
        ),
    ]
