# Generated by Django 5.2.5 on 2025-10-05 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recepcion', models.CharField(max_length=50)),
                ('fecha_recepcion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.recepcion')),
            ],
        ),
    ]
