# Generated by Django 5.2.8 on 2025-11-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='uom_compra',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('ml', 'ML'), ('litro', 'Litro'), ('kg', 'KG'), ('gramo', 'Gramo')], max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='uom_venta',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('ml', 'ML'), ('litro', 'Litro'), ('kg', 'KG'), ('gramo', 'Gramo')], max_length=10),
        ),
    ]
