# Generated by Django 5.2.5 on 2025-10-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_recepcion_detallerecepcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='alerta_bajo_stock',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='alerta_por_vencer',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='codigo_barras',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='control_por_lote',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='control_por_serie',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='factor_conversion',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ficha_tecnica_url',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen_url',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='impuesto_iva',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='perecible',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_venta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='punto_reorden',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_actual',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_maximo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stock_minimo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad_compra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad_venta',
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('ml', 'ML'), ('litro', 'Litro'), ('kg', 'KG'), ('gramo', 'Gramo')], default='unidad', max_length=10),
        ),
    ]
