# Generated by Django 5.2.8 on 2025-11-06 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0002_initial'),
        ('productos', '0001_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recepcioncompra',
            name='recibido_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallerecepcion',
            name='recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.recepcioncompra'),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='solicitudcompra',
            name='solicitado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recepcioncompra',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.solicitudcompra'),
        ),
        migrations.AddField(
            model_name='detallesolicitud',
            name='solicitud',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.solicitudcompra'),
        ),
    ]
