# Generated by Django 5.2.5 on 2025-11-07 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_initial'),
        ('proveedores', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo',
            field=models.CharField(choices=[('materia_prima', 'Materia Prima'), ('insumo', 'Insumo'), ('servicio', 'Servicio'), ('otros', 'Otros')], default='otros', max_length=50),
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=6, max_digits=18)),
                ('precio_unitario', models.DecimalField(decimal_places=6, max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=6, default=0, editable=False, max_digits=18)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_orden', to='proveedores.ordencompra')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto')),
            ],
        ),
    ]
