# Generated by Django 5.2.5 on 2025-11-08 15:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_alter_ordencompra_total_alter_proveedor_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleordencompra',
            name='cantidad',
            field=models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.AlterField(
            model_name='productoproveedor',
            name='costo',
            field=models.DecimalField(decimal_places=6, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.AlterField(
            model_name='productoproveedor',
            name='lead_time_dias',
            field=models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='productoproveedor',
            name='min_lote',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
    ]
